## Importing the Libraries

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix
%matplotlib inline

## Importing the dataset

In [3]:
df = pd.read_csv('D:/VIT/SEM 4/CSE3008/ML LAB 6/predictive_maintenance.csv')
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  
0                    1551         42.8                0       0   No Failure  
1                    1408         46.3                3       0   No Failure  
2                    1498         49.4                5       0   No Failure  
3                    1433         39.5                7       0   No Failure  
4                    1408         40.0                9       0   No Failure

We will try to predict whether the machine will fail or not. Therefore we will take the second last column in the dataset shown
above as our target variable 


## Encoding categorical variable Machine Type

In [4]:
df['Type'].unique()

array(['M', 'L', 'H'], dtype=object)

In [5]:
def encode_col(col):
    if col=='M':
        return 0
    elif col=='L':
        return 1
    elif col=='H':
        return 2
df['Type']=df['Type'].apply(encode_col)

In [6]:
df.head()

UDI Product ID  Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860     0                298.1                    308.6   
1    2     L47181     1                298.2                    308.7   
2    3     L47182     1                298.1                    308.5   
3    4     L47183     1                298.2                    308.6   
4    5     L47184     1                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  
0                    1551         42.8                0       0   No Failure  
1                    1408         46.3                3       0   No Failure  
2                    1498         49.4                5       0   No Failure  
3                    1433         39.5                7       0   No Failure  
4                    1408         40.0                9       0   No Failure

## Dropping UDI, Product ID and Failure Type column

In [7]:
df.drop(['UDI','Product ID','Failure Type'],axis=1,inplace=True)

In [8]:
df.head()

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0     0                298.1                    308.6                    1551   
1     1                298.2                    308.7                    1408   
2     1                298.1                    308.5                    1498   
3     1                298.2                    308.6                    1433   
4     1                298.2                    308.7                    1408   

   Torque [Nm]  Tool wear [min]  Target  
0         42.8                0       0  
1         46.3                3       0  
2         49.4                5       0  
3         39.5                7       0  
4         40.0                9       0

## Dividing dataset into Independent and Dependent variable

In [9]:
X = df.iloc[:,0:-1].values
y = df.iloc[:,-1].values

## Dividing dataset into Training and Test data

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Feature Scaling

In [11]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training SVM with Linear Kernel

In [12]:
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Checking Model Accuracy

In [13]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[1925    0]
 [  75    0]]
0.9625


In [16]:
classifier.support_vectors_

array([[-1.32894768,  0.10387035,  0.67404102,  4.63871031, -2.5372617 ,
         0.57645854],
       [ 1.99862084, -0.592495  ,  0.33914292, -1.36691364,  1.59087199,
         1.48549518],
       [ 0.33483658,  1.79504335,  1.61175567, -0.84225876,  0.19473918,
         1.78328305],
       ...,
       [ 0.33483658,  1.89452411,  2.080613  , -1.57900816,  1.88215149,
         1.65789869],
       [ 0.33483658,  0.40231265,  0.40612254,  0.21263244, -0.20702565,
         1.87732132],
       [ 0.33483658,  1.84478373,  1.41081682, -0.98179463,  1.18910715,
        -0.26988593]])

In [18]:
classifier.n_support_

array([337, 264])